### ISSUE TITLE
Handle protocol operation names in a case insensitive manner

### ISSUE THREAD

**Issue by tallguy-hackett** [mmmries/gnat#18]
According to the [NATS protocol documentation](http://nats.io/documentation/internals/nats-protocol/), protocol operation names are case insensitive

> NATS protocol operation names are case insensitive, thus `SUB foo 1\r\n` and `sub foo 1\r\n` are equivalent.

**Comment by mmmries** [comment]
😊  I guess I should have read the documentation before starting to write a client

**Comment by mmmries** [comment]
💥 🎉 💛 💥 🎉 💛 💥 🎉 💛 💥 🎉 💛 💥 🎉 💛 

This is fixed now
